---
# use this with 'pre-commit' to run some pre-commit hooks
# setup: 'apt install pre-commit; pre-commit install'
# docs : https://pre-commit.com/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
# we cannot use the standard 'check-yaml' hook,
# as this falis with gitlab's special '!reference' syntax
# and our habit to have jobIDs with colons and dots
- repo: https://github.com/adrienverge/yamllint
  rev: v1.33.0
  hooks:
  - id: yamllint
    args: [-d relaxed]
